package com.example.rocketapp;

import com.google.firebase.firestore.Exclude;

public class Trial {

    private String id;  // Generated by firestore
    private String description;
    private User owner;

    public Trial() { }

    public Trial(String description, User owner) {
        this.description = description;
        this.owner = owner;
    }

    public String getDescription() {
        return description;
    }

    public User getOwner() {
        return owner;
    }

    @Exclude
    public String getId() {
        return id;
    }

    @Exclude
    public void setId(String id) {
        this.id = id;
    }


}
